version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build:
      context: ./frontend/admin-dashboard
    ports:
      - "3000:3000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
